language: node_js
os:
- linux
- osx
sudo: false
node_js:
- node
addons:
  apt:
    packages:
      - snapd
script:
- yarn install
- yarn run dist
deploy:
  provider: snap
  snap: dist/pall.snap
  channel: edge
  skip_cleanup: true
  on:
    condition: $TRAVIS_OS_NAME = linux
