environment:
  nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install

test_script:
  - node --version
  - yarn --version
  - yarn run dist

build: off

deploy:
  description: 'Pick a color. Anywhere'
  provider: GitHub
  auth_token:
    secure: j2bKpbxlfzqppu+CEeoJROgO8ZSv1qJXm9r1LCy4zQL/Y1rhMZZfdhcSm+J+bqmG
  artifact: /.*\.exe/
  on:
    branch: master
    appveyor_repo_tag: true